
package com.bmtc.wsdlATP.BMTC;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BMTCSoap", targetNamespace = "BMTC")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BMTCSoap {


    /**
     * 
     * @return
     *     returns bmtc.ArrayOfUserInfo
     */
    @WebMethod(operationName = "GetUserLists", action = "BMTC/GetUserLists")
    @WebResult(name = "GetUserListsResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetUserLists", targetNamespace = "BMTC", className = "bmtc.GetUserLists")
    @ResponseWrapper(localName = "GetUserListsResponse", targetNamespace = "BMTC", className = "bmtc.GetUserListsResponse")
    public ArrayOfUserInfo getUserLists();

    /**
     * 
     * @return
     *     returns bmtc.ArrayOfString
     */
    @WebMethod(operationName = "GetAllProducts", action = "BMTC/GetAllProducts")
    @WebResult(name = "GetAllProductsResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetAllProducts", targetNamespace = "BMTC", className = "bmtc.GetAllProducts")
    @ResponseWrapper(localName = "GetAllProductsResponse", targetNamespace = "BMTC", className = "bmtc.GetAllProductsResponse")
    public ArrayOfString getAllProducts();

    /**
     * 
     * @return
     *     returns bmtc.ArrayOfString
     */
    @WebMethod(operationName = "GetBatchList", action = "BMTC/GetBatchList")
    @WebResult(name = "GetBatchListResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetBatchList", targetNamespace = "BMTC", className = "bmtc.GetBatchList")
    @ResponseWrapper(localName = "GetBatchListResponse", targetNamespace = "BMTC", className = "bmtc.GetBatchListResponse")
    public ArrayOfString getBatchList();

    /**
     * 
     * @return
     *     returns bmtc.ArrayOfRound
     */
    @WebMethod(operationName = "GetRoundList", action = "BMTC/GetRoundList")
    @WebResult(name = "GetRoundListResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetRoundList", targetNamespace = "BMTC", className = "bmtc.GetRoundList")
    @ResponseWrapper(localName = "GetRoundListResponse", targetNamespace = "BMTC", className = "bmtc.GetRoundListResponse")
    public ArrayOfRound getRoundList();

    /**
     * 
     * @param password
     * @param produceID
     * @param loginName
     * @param departmentID
     * @param teamID
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateATPUser", action = "BMTC/CreateATPUser")
    @WebResult(name = "CreateATPUserResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "CreateATPUser", targetNamespace = "BMTC", className = "bmtc.CreateATPUser")
    @ResponseWrapper(localName = "CreateATPUserResponse", targetNamespace = "BMTC", className = "bmtc.CreateATPUserResponse")
    public String createATPUser(
        @WebParam(name = "userName", targetNamespace = "BMTC")
        String userName,
        @WebParam(name = "loginName", targetNamespace = "BMTC")
        String loginName,
        @WebParam(name = "password", targetNamespace = "BMTC")
        String password,
        @WebParam(name = "departmentID", targetNamespace = "BMTC")
        int departmentID,
        @WebParam(name = "teamID", targetNamespace = "BMTC")
        int teamID,
        @WebParam(name = "produceID", targetNamespace = "BMTC")
        ArrayOfInt produceID);

    /**
     * 
     * @param userID
     * @return
     *     returns bmtc.ArrayOfOrganization
     */
    @WebMethod(operationName = "GetUserProducts", action = "BMTC/GetUserProducts")
    @WebResult(name = "GetUserProductsResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "GetUserProducts", targetNamespace = "BMTC", className = "bmtc.GetUserProducts")
    @ResponseWrapper(localName = "GetUserProductsResponse", targetNamespace = "BMTC", className = "bmtc.GetUserProductsResponse")
    public ArrayOfOrganization getUserProducts(
        @WebParam(name = "userID", targetNamespace = "BMTC")
        int userID);

    /**
     * 
     * @param jsonCaseList
     * @param scriptSVNPath
     * @param password
     * @param productID
     * @param batchID
     * @param repository
     * @param userID
     * @param productName
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SaveATPCases", action = "BMTC/SaveATPCases")
    @WebResult(name = "SaveATPCasesResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "SaveATPCases", targetNamespace = "BMTC", className = "bmtc.SaveATPCases")
    @ResponseWrapper(localName = "SaveATPCasesResponse", targetNamespace = "BMTC", className = "bmtc.SaveATPCasesResponse")
    public String saveATPCases(
        @WebParam(name = "batchID", targetNamespace = "BMTC")
        int batchID,
        @WebParam(name = "productID", targetNamespace = "BMTC")
        int productID,
        @WebParam(name = "jsonCaseList", targetNamespace = "BMTC")
        ArrayOfString jsonCaseList,
        @WebParam(name = "userID", targetNamespace = "BMTC")
        int userID,
        @WebParam(name = "scriptSVNPath", targetNamespace = "BMTC")
        String scriptSVNPath,
        @WebParam(name = "productName", targetNamespace = "BMTC")
        String productName,
        @WebParam(name = "repository", targetNamespace = "BMTC")
        String repository,
        @WebParam(name = "username", targetNamespace = "BMTC")
        String username,
        @WebParam(name = "password", targetNamespace = "BMTC")
        String password);

    /**
     * 
     * @param json
     * @return
     *     returns boolean
     */
    @WebMethod(action = "BMTC/testJson2Class")
    @WebResult(name = "testJson2ClassResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "testJson2Class", targetNamespace = "BMTC", className = "bmtc.TestJson2Class")
    @ResponseWrapper(localName = "testJson2ClassResponse", targetNamespace = "BMTC", className = "bmtc.TestJson2ClassResponse")
    public boolean testJson2Class(
        @WebParam(name = "json", targetNamespace = "BMTC")
        String json);

    /**
     * 
     * @param deviceType
     * @param productID
     * @param caseNum
     * @param batchID
     * @param repository
     * @param userID
     * @param productName
     * @param scriptSVNPath
     * @param password
     * @param caseName
     * @param udid
     * @param testClientIP
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UploadATPTasks", action = "BMTC/UploadATPTasks")
    @WebResult(name = "UploadATPTasksResult", targetNamespace = "BMTC")
    @RequestWrapper(localName = "UploadATPTasks", targetNamespace = "BMTC", className = "bmtc.UploadATPTasks")
    @ResponseWrapper(localName = "UploadATPTasksResponse", targetNamespace = "BMTC", className = "bmtc.UploadATPTasksResponse")
    public boolean uploadATPTasks(
        @WebParam(name = "batchID", targetNamespace = "BMTC")
        int batchID,
        @WebParam(name = "productID", targetNamespace = "BMTC")
        int productID,
        @WebParam(name = "caseNum", targetNamespace = "BMTC")
        String caseNum,
        @WebParam(name = "caseName", targetNamespace = "BMTC")
        String caseName,
        @WebParam(name = "userID", targetNamespace = "BMTC")
        int userID,
        @WebParam(name = "scriptSVNPath", targetNamespace = "BMTC")
        String scriptSVNPath,
        @WebParam(name = "TestClientIP", targetNamespace = "BMTC")
        String testClientIP,
        @WebParam(name = "DeviceType", targetNamespace = "BMTC")
        String deviceType,
        @WebParam(name = "UDID", targetNamespace = "BMTC")
        String udid,
        @WebParam(name = "productName", targetNamespace = "BMTC")
        String productName,
        @WebParam(name = "repository", targetNamespace = "BMTC")
        String repository,
        @WebParam(name = "username", targetNamespace = "BMTC")
        String username,
        @WebParam(name = "password", targetNamespace = "BMTC")
        String password);

}
